# -*- coding: utf-8 -*-
"""student performance

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y-9osLLZKqyPK6MurOSL85Chq-RZ1h5c
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import pandas as pd
df=pd.read_csv("/content/StudentsPerformance.csv")

df.head()

df.tail()

df.info()

df.describe()

df.isnull().sum()

df.dropna()

df.columns

df.shape

score_columns=['math score','reading score','writing score']

score_columns

df[score_columns].describe()

df[score_columns].median()

df[score_columns].mode()

df[score_columns].std()

df[score_columns].quantile(0.25)

df["Total Score"]=(df["math score"]+df["reading score"]+df["writing score"])

df.columns

df["Percentage"]=(df["Total Score"]/300)*100

df[["Total Score","Percentage"]].head()

score_columns= ['math score','reading score','writing score']
for col in score_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print("\n", col)
    print("Lower Limit:", lower)
    print("Upper Limit:", upper)
    print("Number of Outliers:", len(outliers))

print("\nFinal Dataset:")
print(df.head())