# -*- coding: utf-8 -*-
"""health care 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gqNYCokg9F19FQ81Iq27eHaL-9H7rXse
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/healthcare_dataset (2).csv")
df.head()

df.info()

df.describe()

df.isnull().sum()

df.columns

df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Year_Month'] = df['Date of Admission'].dt.to_period('M')
monthly_admissions = df.groupby('Year_Month').size()
monthly_admissions.head()

peak_month = monthly_admissions.idxmax()
peak_admissions = monthly_admissions.max()

print("Peak Admission Month:", peak_month)
print("Number of Admissions:", peak_admissions)

billing_data = df.groupby(
    ['Medical Condition', 'Insurance Provider']
)['Billing Amount'].sum().unstack(fill_value=0)

billing_data.plot(
    kind='bar',
    stacked=True,
    figsize=(12, 6)
)

plt.title('Billing Amount by Medical Condition and Insurance Provider')
plt.xlabel('Medical Condition')
plt.ylabel('Total Billing Amount')
plt.xticks(rotation=45)
plt.legend(title='Insurance Provider')
plt.tight_layout()
plt.show()

# Removed redundant import pandas as pd, df=pd.read_csv("/content/healthcare_dataset (1).csv") and import seaborn as sns
plt.figure(figsize=(12, 6))
sns.violinplot(
    data=df,
    x='Medical Condition',
    y='Billing Amount'
)

# Removed redundant import matplotlib.pyplot as plt
plt.title('Billing Amount Distribution by Medical Condition')
plt.xlabel('Medical Condition')
plt.ylabel('Billing Amount')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 6))

sns.violinplot(
    data=df,
    x='Insurance Provider',
    y='Billing Amount'
)

plt.title('Billing Amount Distribution by Insurance Provider')
plt.xlabel('Insurance Provider')
plt.ylabel('Billing Amount')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

print("Average Billing Amount by Medical Condition:")

print(df.groupby('Medical Condition')['Billing Amount'].mean())

print("\nAverage Billing Amount by Insurance Provider:")

print(df.groupby('Insurance Provider')['Billing Amount'].mean())