# -*- coding: utf-8 -*-
"""shopify stock

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xpw85DrsYmm4Lenx7YiEFMGCFwkAfxlv
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('/content/shopify_stock.csv')
display(df.head())

import matplotlib.pyplot as plt
import seaborn as sns
df['date'] = pd.to_datetime(df['date'])
sns.set_style('whitegrid')
plt.figure(figsize=(14, 7))
sns.lineplot(x='date', y='close', data=df)
plt.title('Shopify Closing Price Over Time', fontsize=16)
plt.xlabel('Date', fontsize=12)
plt.ylabel('Closing Price (USD)', fontsize=12)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
df['MA_20'] = df['close'].rolling(20).mean()
df['MA_50'] = df['close'].rolling(50).mean()
sns.lineplot(x='date', y='close', data=df, label='Close')
sns.lineplot(x='date', y='MA_20', data=df, label='MA 20')
sns.lineplot(x='date', y='MA_50', data=df, label='MA 50')
plt.title('Shopify Closing Price & Moving Averages')
plt.xlabel('Date')
plt.ylabel('Price (USD)')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

df['daily_returns'] = df['close'].pct_change()
display(df.head())

import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')
plt.figure(figsize=(12, 6))
sns.histplot(df['daily_returns'].dropna(), bins=50, color='skyblue')
plt.title('Distribution of Shopify Daily Returns', fontsize=16)
plt.xlabel('Daily Return', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.tight_layout()
plt.show()