# -*- coding: utf-8 -*-
"""apple stock

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GPJVDtZTSUtwFIzSJZYYEsyqkDIs0Vb1
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np

df=pd.read_csv('AAPL.csv')

df.head()

df.isnull().sum()

