# -*- coding: utf-8 -*-
"""hospital health care

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mn9m2GrfymAsShAAtFMWhifAH7zslkLK
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn  as sns

df=pd.read_csv("/content/healthcare_dataset.csv")
df

df['Medical_Code'].isnull()

print(df['Medical_Code'].value_counts())

df['Standardized_Medical_Code'] = df['Medical_Code'].str.replace('ICD-10-', '')
print(df[['Medical_Code', 'Standardized_Medical_Code']].head())

df['Admission_Date'] = pd.to_datetime(df['Admission_Date'], format='%d-%m-%Y')
df['Discharge_Date'] = pd.to_datetime(df['Discharge_Date'], format='%d-%m-%Y')
df['Hospital_Stay_Days'] = (df['Discharge_Date'] - df['Admission_Date']).dt.days
display(df[['Admission_Date', 'Discharge_Date', 'Hospital_Stay_Days']].head())

print("Summary Statistics for Billing Amount:")
display(df['Billing_Amount'].describe())
print("\nSummary Statistics for Hospital Stay Days:")
display(df['Hospital_Stay_Days'].describe())

df['Hospital_Stay_Days']=(df['Discharge_Date']-df['Admission_Date']).dt.days
print(df['Billing_Amount'].describe())
print(df['Hospital_Stay_Days'].describe())

